// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqdrDuTZhV4IqnrwCRHefYQ51d5whf5Mo',
    appId: '1:1046190429515:web:2556945835910295d284ce',
    messagingSenderId: '1046190429515',
    projectId: 'litlens-a0f5b',
    authDomain: 'litlens-a0f5b.firebaseapp.com',
    storageBucket: 'litlens-a0f5b.firebasestorage.app',
    measurementId: 'G-BJHYKJKG39',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVfDXfkPOca4WsCld0s9OcRztjdEHGl8g',
    appId: '1:1046190429515:android:91992e09d94bce9dd284ce',
    messagingSenderId: '1046190429515',
    projectId: 'litlens-a0f5b',
    storageBucket: 'litlens-a0f5b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJJjD9XgALLSakxiczS6ON36lLIn3xW80',
    appId: '1:1046190429515:ios:021ae22cb6bba506d284ce',
    messagingSenderId: '1046190429515',
    projectId: 'litlens-a0f5b',
    storageBucket: 'litlens-a0f5b.firebasestorage.app',
    iosClientId: '1046190429515-ugo2vg09int87j5ee63aftks1c44cdrv.apps.googleusercontent.com',
    iosBundleId: 'com.example.litlensV1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJJjD9XgALLSakxiczS6ON36lLIn3xW80',
    appId: '1:1046190429515:ios:021ae22cb6bba506d284ce',
    messagingSenderId: '1046190429515',
    projectId: 'litlens-a0f5b',
    storageBucket: 'litlens-a0f5b.firebasestorage.app',
    iosClientId: '1046190429515-ugo2vg09int87j5ee63aftks1c44cdrv.apps.googleusercontent.com',
    iosBundleId: 'com.example.litlensV1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqdrDuTZhV4IqnrwCRHefYQ51d5whf5Mo',
    appId: '1:1046190429515:web:6a1f005a78822277d284ce',
    messagingSenderId: '1046190429515',
    projectId: 'litlens-a0f5b',
    authDomain: 'litlens-a0f5b.firebaseapp.com',
    storageBucket: 'litlens-a0f5b.firebasestorage.app',
    measurementId: 'G-G0YV9PW29M',
  );
}